enableGlobalCache: true

enableTelemetry: false

npmScopes:
  thm:
    npmAlwaysAuth: true
    npmPublishRegistry: "https://myprivateregistry.jfrog.io/npm-prod/"
    npmRegistryServer: "https://myprivateregistry.jfrog.io/npm-prod/"

npmRegistries:
  "//myprivateregistry.jfrog.io/npm-prod/":
    npmAuthIdent: "SOME_PASSWORD"

yarnPath: .yarn/releases/yarn-3.0.0-rc.2.cjs
